on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build-packagegroup-meta-python:
    runs-on: docker
    container:
      image: tgamblin/yocto-builder
      volumes:
        - /auto/runner/buildcache:/buildcache
    steps:
      - name: build packagegroup-meta-python
        run: |
          locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          git clone https://git.lab.ecocode.site/tgamblin/workflows.git .
          git clone https://git.lab.ecocode.site/tgamblin/openembedded-core.git
          git clone https://git.lab.ecocode.site/tgamblin/bitbake.git openembedded-core/bitbake
          git clone https://git.lab.ecocode.site/tgamblin/meta-openembedded.git
          cd openembedded-core && source oe-init-build-env
          bitbake-layers add-layer ../../meta-openembedded/meta-oe
          bitbake-layers add-layer ../../meta-openembedded/meta-python
          echo "DL_DIR = \"/buildcache/downloads\"" >> conf/local.conf
          echo "SSTATE_DIR = \"/buildcache/sstate-cache\"" >> conf/local.conf
          bitbake -k packagegroup-meta-python
