on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  meta-python-build-and-test:
    runs-on: docker
    container:
      image: tgamblin/yocto-builder
      volumes:
        - /auto/runner/buildcache:/buildcache
      options: --device=/dev/kvm
    steps:
      - name: build packagegroup-meta-python
        run: |
          locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          git clone https://git.lab.ecocode.site/tgamblin/workflows.git .
          git clone https://git.lab.ecocode.site/tgamblin/openembedded-core.git
          git clone https://git.lab.ecocode.site/tgamblin/bitbake.git openembedded-core/bitbake
          git clone https://git.lab.ecocode.site/tgamblin/meta-openembedded.git
          git clone https://git.lab.ecocode.site/tgamblin/meta-yocto.git
          cd openembedded-core && source oe-init-build-env
          bitbake-layers add-layer ../../meta-yocto/meta-poky
          bitbake-layers add-layer ../../meta-openembedded/meta-oe
          bitbake-layers add-layer ../../meta-openembedded/meta-python
          echo "DL_DIR = \"/buildcache/downloads\"" >> conf/local.conf
          echo "SSTATE_DIR = \"/buildcache/sstate-cache\"" >> conf/local.conf
          echo "DISTRO = \"poky\"" >> conf/local.conf
          bitbake -k packagegroup-meta-python
        continue-on-error: true

      - name: build meta-python-ptest-image-all
        run: |
          cd openembedded-core && source oe-init-build-env
          bitbake meta-python-image-ptest-all

      - name: run testimage
        run: |
          cd openembedded-core && source oe-init-build-env
          echo "QEMU_USE_KVM ?= \"1\"" >> conf/local.conf
          echo "QEMU_USE_SLIRP ?= \"1\"" >> conf/local.conf
          echo "TEST_RUNQEMUPARAMS:append = \" nographic\"" >> conf/local.conf
          echo "TEST_SUITES = \"ping ssh ptest\"" >> conf/local.conf
          echo "IMAGE_CLASSES += \"testimage\"" >> conf/local.conf
          mkdir testimage_logs
          meta_python_ptest_recipes=$(bitbake-layers show-recipes --recipes-only --layer meta-python --inherits ptest --bare | tr '\n' ' ' | pcregrep -o1 '^NOTE:.+===(.+)$')
          for package in $meta_python_ptest_recipes; do bitbake -c meta-python-image-ptest-$package 2>&1 | tee testimage_logs/testimage_$package.log; done

      - name: upload testimage logs
        uses: actions/upload-artifact@v4
        with:
          name: testimage_logs
          path: openembedded-core/build/testimage_logs
