on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  build-riscv-image:
    runs-on: docker
    strategy:
      matrix:
        machine: ['orangepi-rv2-mainline', 'bananapi-f3', 'nezha-allwinner-d1']
    container:
      image: tgamblin/yocto-builder
      volumes:
        - /auto/runner/buildcache:/buildcache
    steps:
      - name: build core-image-full-cmdline
        run: |
          locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          git clone https://git.lab.ecocode.site/tgamblin/workflows.git .
          git clone https://git.lab.ecocode.site/tgamblin/openembedded-core.git
          git clone https://git.lab.ecocode.site/tgamblin/bitbake.git openembedded-core/bitbake
          git clone https://git.lab.ecocode.site/tgamblin/meta-riscv.git
          cd openembedded-core && source oe-init-build-env
          bitbake-layers add-layer ../../meta-riscv
          echo "DL_DIR = \"/buildcache/downloads\"" >> conf/local.conf
          echo "SSTATE_DIR = \"/buildcache/sstate-cache\"" >> conf/local.conf
          MACHINE=${RISCV_MACHINE} bitbake core-image-full-cmdline
        env:
          RISCV_MACHINE: ${{matrix.machine}}

      - name: copy kernel and dtb to TFTP server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TFTP_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          BOARD="${RISCV_MACHINE%-mainline}"
          scp openembedded-core/build/tmp/deploy/images/${RISCV_MACHINE}/Image auto@ecovault.oryx-coho.ts.net:/srv/tftp/${BOARD}/Image
          scp openembedded-core/build/tmp/deploy/images/${RISCV_MACHINE}/*.dtb auto@ecovault.oryx-coho.ts.net:/srv/tftp/${BOARD}/
        env:
          RISCV_MACHINE: ${{matrix.machine}}
