on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  build-riscv-image:
    runs-on: docker
    strategy:
      matrix:
        machine: ['orangepi-rv2-mainline', 'bananapi-f3', 'nezha-allwinner-d1']
    container:
      image: tgamblin/yocto-builder
      volumes:
        - /auto/runner/buildcache:/buildcache
    steps:
      - name: build core-image-full-cmdline
        run: |
          locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          git clone https://git.lab.ecocode.site/tgamblin/workflows.git .
          git clone https://git.lab.ecocode.site/tgamblin/openembedded-core.git
          git clone https://git.lab.ecocode.site/tgamblin/bitbake.git openembedded-core/bitbake
          git clone https://git.lab.ecocode.site/tgamblin/meta-riscv.git
          cd openembedded-core && source oe-init-build-env
          bitbake-layers add-layer ../../meta-riscv
          echo "DL_DIR = \"/buildcache/downloads\"" >> conf/local.conf
          echo "SSTATE_DIR = \"/buildcache/sstate-cache\"" >> conf/local.conf
          MACHINE=${RISCV_MACHINE} bitbake core-image-full-cmdline
        env:
          RISCV_MACHINE: ${{matrix.machine}}

      - name: copy kernel and dtb to TFTP server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TFTP_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          BOARD="${RISCV_MACHINE%-mainline}"
          scp openembedded-core/build/tmp/deploy/images/${RISCV_MACHINE}/Image auto@ecovault.oryx-coho.ts.net:/srv/tftp/${BOARD}/Image
          scp openembedded-core/build/tmp/deploy/images/${RISCV_MACHINE}/*.dtb auto@ecovault.oryx-coho.ts.net:/srv/tftp/${BOARD}/
        env:
          RISCV_MACHINE: ${{matrix.machine}}

  test-board-boot:
    runs-on: docker
    strategy:
      matrix:
        machine: ['orangepi-rv2-mainline']
    container:
      image: tgamblin/lg-operator
      options: --add-host ecogrid:192.168.40.101 --add-host lg-exporter-1:192.168.40.176
    steps:
      - name: set up keys
        working-directory: /home/lg-operator
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LG_EXPORTER_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.LG_EXPORTER_1_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa

      - name: test SSH connection
        working-directory: /home/lg-operator
        run: |
          echo "=== SSH directory contents ==="
          ls -la ~/.ssh/
          echo "=== Known hosts ==="
          cat ~/.ssh/known_hosts
          echo "=== Testing SSH connection ==="
          ssh -v labgrid@lg-exporter-1 "echo SSH connection successful"

      - name: clone labgrid-power-up
        working-directory: /home/lg-operator
        run: |
          git clone https://git.lab.ecocode.site/tgamblin/labgrid-power-up.git

      - name: set up virtualenv
        working-directory: /home/lg-operator/labgrid-power-up
        run: |
          python3 -m venv venv && source venv/bin/activate
          pip install --upgrade pip
          pip install labgrid pytest pytest-html

      - name: run labgrid-client
        working-directory: /home/lg-operator/labgrid-power-up
        run: |
          source venv/bin/activate
          eval `labgrid-client reserve --shell machine=$RISCV_MACHINE`
          echo $LG_TOKEN
          labgrid-client wait
          labgrid-client -p + lock
          labgrid-client -p + show
          BOARD="${RISCV_MACHINE%-mainline}"
          pytest -v --html=report.html --self-contained-html --lg-env boardfarm/$BOARD/$BOARD-client.yaml boardfarm/$BOARD/pytest/test_tftp.py
          labgrid-client -p + release
        env:
          LG_COORDINATOR: ecogrid
          RISCV_MACHINE: ${{matrix.machine}}
