on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  test-board-boot:
    runs-on: docker
    strategy:
      matrix:
        machine: ['orangepi-rv2-mainline']
    container:
      image: tgamblin/lg-operator
      options: --add-host ecogrid:192.168.40.101 --add-host lg-exporter-1:192.168.40.176
    steps:
      - name: set up keys
        working-directory: /home/labgrid
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LG_EXPORTER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan lg-exporter-1 >> ~/.ssh/known_hosts 2>/dev/null
          ssh-keyscan 100.91.92.1 >> ~/.ssh/known_hosts 2>/dev/null

      - name: test SSH connection
        working-directory: /home/labgrid
        run: |
          # Check if the key is encrypted
          grep "ENCRYPTED" ~/.ssh/id_rsa || echo "Key is not encrypted"

          # Try with explicit key and BatchMode
          ssh -o BatchMode=yes -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa -v labgrid@lg-exporter-1 "echo SSH connection successful"
          echo "=== SSH directory contents ==="
          ls -la ~/.ssh/
          echo "=== Known hosts ==="
          cat ~/.ssh/known_hosts
          echo "=== Testing SSH connection ==="
          ssh -v labgrid@lg-exporter-1 "echo SSH connection successful"

      - name: clone labgrid-power-up
        working-directory: /home/labgrid
        run: |
          git clone -b rv2-fix https://github.com/threexc/labgrid-power-up.git

      - name: set up virtualenv
        working-directory: /home/labgrid/labgrid-power-up
        run: |
          python3 -m venv venv && source venv/bin/activate
          pip install --upgrade pip
          pip install labgrid pytest pytest-html

      - name: run labgrid-client
        working-directory: /home/labgrid/labgrid-power-up
        run: |
          source venv/bin/activate
          eval `labgrid-client reserve --shell machine=$RISCV_MACHINE`
          echo $LG_TOKEN
          labgrid-client wait
          labgrid-client -p + lock
          labgrid-client -p + show
          BOARD="${RISCV_MACHINE%-mainline}"
          for i in {1..3}; do
            echo "pytest attempt $i of 3"
            if pytest -vvv --html=report.html --self-contained-html --lg-env boardfarm/$BOARD/$BOARD-client.yaml boardfarm/$BOARD/pytest/test_tftp.py; then
              echo "Tests passed on attempt $i"
              exit 0
            fi
            echo "Attempt $i failed, retrying..."
            sleep 5
          done
          echo "All pytest attempts failed"
          labgrid-client -p + release
          exit 1
        env:
          LG_COORDINATOR: ecogrid
          RISCV_MACHINE: ${{matrix.machine}}
